name: Publish Package
on:
  push:
    tags:
      - '*'

jobs:
  publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        framework: ['react']
    steps:
      - uses: actions/checkout@v6

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: 24
          cache: 'pnpm'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: 'Build ${{ matrix.framework }}'
        run: pnpm --filter ./packages/${{ matrix.framework }} run build

      - name: 'Publish ${{ matrix.framework }} to npm'
        run: pnpm --filter ./packages/${{ matrix.framework }} publish --no-git-checks --access public
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
